# Generated by Django 2.2.1 on 2019-05-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190512_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.QnA'),
        ),
    ]
